paths:
  # - "/home/nischal/dev/prometheus-filestat"
  # - "/home/nischal/dev/ecommerce"
  # - /home/nischal/dev/inventory_management
  # - /home/nischal/dev/inventory_management_frontend
  # - /inventory_mgmt_fronten
  - /protected